# Generated by Django 3.0.6 on 2020-06-07 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=280)),
                ('once_upon_a_time', models.CharField(max_length=280)),
                ('every_day', models.CharField(max_length=280)),
                ('one_day', models.CharField(max_length=280)),
                ('result', models.CharField(max_length=280)),
                ('result2', models.CharField(max_length=280)),
                ('until_finally', models.CharField(max_length=280)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stories.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='UserStory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('story', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stories.Story')),
            ],
        ),
    ]
